// frontend/minimal-frontend-demo/06-store/vue-pinia/src/pages/TodosPage.vue
<script setup lang="ts">
    import { ref } from 'vue'

    // 引入 store
    import { useCounterStore } from '../store/counter'
    // 获取 store 实例，使用 counter 这个全局仓库
    const counter = useCounterStore()

    const todos = ref<string[]>([])
    const input = ref("")

    // 添加todo
    function addTodo() {

        // 1、输入验证
        const content = input.value.trim()
        if (!content) {
            return
        }

        // 2、加入 todos
        todos.value.push(content)

        // 3、清空输入框
        input.value = ""

    }

    // 移除todo
    function removeTodo(index: number) {
        todos.value.splice(index, 1)
    }


</script>


<template>
    <h1>todo</h1>
    
    <section>
        <p>共享counter: {{ counter.count }}</p>
        <input v-model="input" type="text">
            <button @click="addTodo()">add</button>

            <ul>
                <li v-for="(todo, index) in todos" :key="index">

                    {{ todo }}
                    <button @click="removeTodo(index)">删除</button>

                </li>

            </ul>

    </section>
</template>

// frontend/minimal-frontend-demo/06-store/react-zustand/src/pages/TodosPage.tsx
import { useState } from "react";
import { useCounterStore } from "../store/counter";

export function TodosPage() {
  
  const counter = useCounterStore((state) => state.count);

  // todo状态
  const [input, setInput] = useState<string>("");
  const [todos, setTodos] = useState<string[]>([]);

  function addTodo() {
    // 1、数据检查
    const newTodo = input.trim();
    if (!newTodo) {
      return;
    }

    // 2、加入 todos
    setTodos((prevTodos) => [...prevTodos, newTodo]);

    // 3、清空输入框
    setInput("");
  }

  function removeTodo(index: number) {
    setTodos((prevTodos) =>
      prevTodos.filter((_, currentIndex) => currentIndex !== index),
    );
  }

  return (
    <>
      <h1>待办</h1>
      <p>共享counter: { counter }</p>
      <section>
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          type="text"
        />

        {/* 函数没有参数的话，可以不使用箭头函数 */}
        <button onClick={addTodo}>添加</button>

        <ul>
          {todos.map((todo: string, index: number) => (
            <li key={index}>
              {todo}
              <button onClick={() => removeTodo(index)}>删除</button>
            </li>
          ))}
        </ul>
      </section>
    </>
  );
}
