// frontend/minimal-frontend-demo/05-router/react/src/pages/CounterPage.tsx
import { useState } from "react";

export function CounterPage() {
  // 计数器状态
  const [counter, setCounter] = useState<number>(0);

  return (
    <>
      <h1>计数器</h1>
      <section>
        <span>当前计数：{counter}</span>
        <button onClick={() => setCounter((prevCounter) => prevCounter + 1)}>
          +1
        </button>
      </section>
    </>
  );
}

// frontend/minimal-frontend-demo/06-store/vue-pinia/src/pages/CounterPage.vue
<script setup lang="ts">
    // 引入 store
    import { useCounterStore } from '../store/counter'
    // 获取 store 实例，使用 counter 这个全局仓库
    const counter = useCounterStore()
</script>

<template>
    <h1>计数器</h1>
    <section>
        <p>当前计数：{{ counter.count }}</p>

        <button @click="counter.increase()">+1</button>
        <button @click="counter.reset()">重置</button>

    </section>
</template>
